name: catraca ci nativo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: jdk setup
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: build
      run: |
        cd src
        javac -cp . Main.java
        javac -cp . Testes.java
    - name: exec
      run: |
        cd src
        java -cp . Testes
        
     # versionamento 1
    - name : gerando versao
      run: echo ${{ github.run_number }}
    
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: subindo no docker
      with:
        image: ${{secrets.DOCKER_USER}}/catraca
        tags: latest, ${{ github.run_number }}
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
       
